### PR TITLE
Private projects not visible on landing

### PR DESCRIPTION
**Pull request by nicole-gathany**
I still need to make the private projects visible to the user

### CODE REVIEW

**Comment by nicole-gathany** [comment]
I was originally going to create a seperate component for the current user view but realized that was unnecessary.

**Comment by abrie** [comment]
Looks good to me. All it needs is code formatting.
We have a standard `.prettierrc` configuration in the root of the project.
Assuming you have Prettier installed, you can apply the rules through the CLI:
`prettier --write src/components/Projects/table.js`

**Comment by nicole-gathany** [comment]
> Looks good to me. All it needs is code formatting.
> We have a standard `.prettierrc` configuration in the root of the project.
> Assuming you have Prettier installed, you can apply the rules through the CLI:
> `prettier --write src/components/Projects/table.js`

Ok. I actually need to reinstall prettier

**Comment by nicole-gathany** [comment]
> --write src/components/Projects/table.js

this is actually not working for me. it's saying prettier is not a command.

**Pull request merged**
